name: Reservation Request
description: Submit a new reservation request
title: '[Reservation] New Reservation Request'
labels:
  - reservation
projects:
  - issue-ops/2
body:
  - type: markdown
    attributes:
      value: |
        Welcome to Bear Creek Honey Farm! Please fill out the following information to request a new reservation.

        Please note that this is just a technical demonstration. We are not taking reservations because we do not exist.
  - type: input
    id: start
    attributes:
      label: Check-In Date (MM/DD/YYYY)
      description: Check-in date for your reservation
      placeholder: 01/01/2025
    validations:
      required: true
  - type: input
    id: end
    attributes:
      label: Check-Out Date (MM/DD/YYYY)
      description: Check-out date for your reservation
      placeholder: 01/10/2025
    validations:
      required: true
  - type: input
    id: guests
    attributes:
      label: Number of Guests
      description: Total number of guests in your party
      placeholder: '2'
    validations:
      required: true
  - type: dropdown
    id: room
    attributes:
      label: Room Type
      description: Select the type of room you would like to reserve
      multiple: false
      options:
        - Single Queen
        - Double Queen
        - King Suite
    validations:
      required: true
  - type: checkboxes
    id: amenities
    attributes:
      label: Amenities
      description: Select any amenities you would like included
      options:
        - label: Breakfast
        - label: Lunch
        - label: Dinner
        - label: Wi-Fi
