name: Continuous Delivery

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  release:
    name: Release Version
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'dependabot/') == false)

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Tag
        id: tag
        uses: issue-ops/semver@v2
        with:
          manifest-path: package.json
          workspace: ${{ github.workspace }}
          ref: main

      - name: Create Release
        id: release
        uses: issue-ops/releaser@v2
        with:
          tag: v${{ steps.tag.outputs.version }}

      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Build
        id: build
        run: npm run build

      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: out
          token: ${{ secrets.GITHUB_TOKEN }}
