name: Continuous Delivery

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    name: Build Next.js App
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'dependabot/') == false)

    steps:
      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
        with:
          fetch-tags: true

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Build
        id: build
        run: npm run build

      - name: Upload Artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release:
    name: Release Version
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
        with:
          fetch-tags: true

      - name: Tag
        id: tag
        uses: issue-ops/semver@v2
        with:
          manifest-path: package.json
          workspace: ${{ github.workspace }}
          ref: main

      - name: Create Release
        id: release
        uses: issue-ops/releaser@v2
        with:
          tag: v${{ steps.tag.outputs.version }}
